Repository cb-technologists/blog, pull requests merged in 2019-07, with the labels that each got.

#23 initial draft of cjd-casc post
  content/posts/cjd-casc.md
  ideas.md
  static/img/cjd-casc/cjd-casc-pipeline.png
Labels: approved, size/XL

#24 added support for canonical metadata that allows cross posts from oth…
  themes/hello-friend-ng/layouts/partials/head.html
Labels: approved, size/XS

#25 added publish date as dimension2 for Google Analytics
  themes/hello-friend-ng/layouts/partials/javascript.html
Labels: approved, size/XS

#26 Introduction to GitOps series - Part 1
  content/posts/gitops-series-part-1.md
  static/img/gitops-series/part-1/plan.svg
  static/img/gitops-series/part-1/trend.png
Labels: approved, lgtm, size/XL

#31 Lightning talks
  content/posts/lightning-talks-dw-jw-2019.md
  static/img/building-container-images-with-kubernetes/secure-containers.jpg
  static/img/technologists.png
  themes/hello-friend-ng/assets/scss/_single.scss
Labels: approved, size/M

#32 Update lightning-talks-dw-jw-2019.md
  content/posts/lightning-talks-dw-jw-2019.md
Labels: approved, size/XS

#34 Trying to fix merge from tekton-jx-orchestration branch
  content/posts/tekton-jx-pipelines.md
  static/img/tekton-jx-orchestration/TektonPipeline_Arch.png
  static/img/tekton-jx-orchestration/jxpipeline-to-tekton.png
  static/img/tekton-jx-orchestration/petclinic-jx_503.png
  static/img/tekton-jx-orchestration/petclinic-jx_pipeline.png
  static/img/tekton-jx-orchestration/petclinic-jx_staging.png
  static/img/tekton-jx-orchestration/petclinic_tekton.png
Labels: approved, lgtm, size/XL

#37 blog post - staying safer with snyk and jenkins
  content/posts/jenkins-snyk.md
  static/img/jenkins-snyk/build-report.png
  static/img/jenkins-snyk/build-step-shell.png
  static/img/jenkins-snyk/build-step-snyk.png
  static/img/jenkins-snyk/cloudbees-logo.png
  static/img/jenkins-snyk/configure-build-step-snyk.png
  static/img/jenkins-snyk/credentials-secret-text.png
  static/img/jenkins-snyk/dwjw.png
  static/img/jenkins-snyk/global-tool.png
  static/img/jenkins-snyk/install-plugin.png
  static/img/jenkins-snyk/jenkins-snyk.png
  static/img/jenkins-snyk/snyk-logo.png
  static/img/jenkins-snyk/snyk-portal.png
  static/img/jenkins-snyk/snyk-web.png
  static/img/jenkins-snyk/snyk-wizard.png
Labels: approved, lgtm, size/L
