Repository cb-technologists/blog, pull requests merged in 2019-05, with the labels that each got.

#1 updated release to use hugo only image
  charts/preview/Chart.yaml
  charts/preview/values.yaml
  jenkins-x.yml
Labels: approved, size/M

#2 added charts
  charts/preview/templates/_helpers.tpl
  charts/preview/templates/deployment.yaml
  charts/preview/templates/service.yaml
  content/posts/introducing-technologists.md
Labels: approved, size/M

#3 update intro
  content/posts/introducing-technologists.md
  jenkins-x.yml
Labels: approved, size/XS

#4 updated push step
  jenkins-x.yml
Labels: approved, size/XS

#5 update intro
  charts/preview/Makefile
  charts/preview/requirements.yaml
  content/posts/introducing-technologists.md
Labels: size/XS

#8 updated baseURL
  Dockerfile
  Jenkinsfile
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  config.toml
  content/posts/introducing-technologists.md
  jenkins-x.yml
Labels: approved, size/L

#9 test
  Makefile
  content/about.md
  skaffold.yaml
  update-website.sh
  watch.sh
Labels: approved, size/L

#10 test
  charts/preview/templates/_helpers.tpl
  charts/preview/templates/deployment.yaml
  charts/preview/templates/service.yaml
Labels: approved, size/M

#12 Update OWNERS - add cvega to reviewers
  OWNERS
Labels: approved, ok-to-test, size/XS

#11 updated introducing-technologists post, added draft publishing for PRs
  content/about.md
  content/posts/introducing-technologists.md
  ideas.md
  jenkins-x.yml
  public/categories/index.xml
  public/index.xml
  public/sitemap.xml
  public/tags/index.xml
  themes/hello-friend-ng/assets/scss/_logo.scss
  themes/hello-friend-ng/layouts/partials/logo.html
Labels: approved, size/M

#15 Post for Jenkins X integration with CloudBees Flow
  content/posts/jenkins-x-flow-integration.md
Labels: approved, lgtm, size/L

#16 Updated draft: false
  content/posts/jenkins-x-flow-integration.md
Labels: approved, size/XS

#17 added google analytics
  config.toml
Labels: approved, size/XS

#13 Jenkins Plugins: The Good, the Bad and the Ugly post
  .gitignore
  README.md
  config.toml
  content/posts/jenkins-plugins-good-bad-ugly.md
  public/404.html
  public/about/index.html
  public/bundle.min.cf7871ed49474a80ed457154d24e61f7881adbe0f9384951a74ac46b688a39a4dbfa68bc6d37baeb058186de354ead3487d4ee7f083ea4cba860c48600b694f3.js
  public/categories/index.html
  public/fonts/Inter-UI-Bold.woff
  public/fonts/Inter-UI-Bold.woff2
  public/fonts/Inter-UI-BoldItalic.woff
  public/fonts/Inter-UI-BoldItalic.woff2
  public/fonts/Inter-UI-Italic.woff
  public/fonts/Inter-UI-Italic.woff2
  public/fonts/Inter-UI-Medium.woff
  public/fonts/Inter-UI-Medium.woff2
  public/fonts/Inter-UI-MediumItalic.woff
  public/fonts/Inter-UI-MediumItalic.woff2
  public/fonts/Inter-UI-Regular.woff
  public/fonts/Inter-UI-Regular.woff2
  public/index.html
  public/main.css.map
  public/main.min.91687bbfc139d7ff1a244bb6d7324425f9c4f424eaaad242b478e3b3cf56396a.css
  public/tags/index.html
  resources/_gen/assets/js/bundle.js_3d041b08546090308b2e5d3a88088713.content
  resources/_gen/assets/js/bundle.js_3d041b08546090308b2e5d3a88088713.json
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.content
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.json
  static/img/jenkins-plugins-good-bad-ugly/jenkins_devil.png
  static/img/jenkins-plugins-good-bad-ugly/wythe-alley-electric-pole.jpg
  themes/hello-friend-ng/assets/scss/_single.scss
  themes/hello-friend-ng/exampleSite/config.toml
  themes/hello-friend-ng/layouts/_default/single.html
  themes/hello-friend-ng/layouts/posts/single.html
  themes/hello-friend-ng/static/css/hugo-easy-gallery.css
  themes/hello-friend-ng/static/js/load-photoswipe.js
Labels: approved, size/XXL

#18 Add author
  config.toml
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.content
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.json
  themes/hello-friend-ng/layouts/posts/single.html
Labels: approved, size/S
