Repository cb-technologists/blog, pull requests merged in 2019-10, with the labels that each got.

#47 update ingress-nginx instructions
  content/posts/best-practices-for-cloudbees-core-jenkins-on-kubernetes/core-psp.md
Labels: approved, lgtm, size/L

#48 Service accounts iam
  content/posts/best-practices-for-cloudbees-core-jenkins-on-kubernetes/bryce-canyon-wall-street.jpg
  content/posts/best-practices-for-cloudbees-core-jenkins-on-kubernetes/securely-using-cloud-services-from-jenkins-kubernetes-agents.md
  static/CNAME
Labels: approved, size/L

#50 fix css for mobile
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.content
  resources/_gen/assets/scss/scss/main.scss_39fa5fe97be74115670eace810202c56.json
  themes/hello-friend-ng/assets/scss/_list.scss
  themes/hello-friend-ng/assets/scss/_series.scss
  themes/hello-friend-ng/assets/scss/_single.scss
  themes/hello-friend-ng/layouts/series/list.html
Labels: approved, size/S

#51 Initial draft of img post
  content/authors/matt-elgin/_index.md
  content/authors/matt-elgin/headshot-melgin.jpeg
  content/posts/building-images-with-img.md
Labels: approved, size/L
