Repository cb-technologists/blog, pull requests merged in 2019-06, with the labels that each got.

#19 Update jenkins-plugins-good-bad-ugly.md
  content/posts/jenkins-plugins-good-bad-ugly.md
Labels: approved, ok-to-test, size/S

#20 first draft of CloudBees' Cross Team Collaboration for Ansynchronous …
  content/posts/cloudbees-cross-team-and-dev-sec-ops.md
  static/img/cloudbees-cross-team-dev-sec-ops/locks.png
  themes/hello-friend-ng/layouts/partials/javascript.html
Labels: approved, lgtm, size/L

#21 typo fixes
  content/posts/cloudbees-cross-team-and-dev-sec-ops.md
Labels: approved, size/S

#22 added ga custom dimension to track author
  themes/hello-friend-ng/layouts/partials/javascript.html
Labels: approved, size/S
